[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="style" type="String" --]
[#-- @ftlvariable name="parent" type="org.asciidoctor.ast.ContentNode" --]
[#-- @ftlvariable name="releases" type="java.util.List<String>" --]
[#-- @ftlvariable name="target" type="String" --]
[#-- @ftlvariable name="home" type="io.helidon.build.maven.sitegen.models.Page" --]
[#-- @ftlvariable name="home.target" type="String" --]
[#-- @ftlvariable name="theme.primary" type="String" --]
[#-- @ftlvariable name="theme.secondary" type="String" --]
[#-- @ftlvariable name="theme.accent" type="String" --]
[#-- @ftlvariable name="theme.error" type="String" --]
[#-- @ftlvariable name="theme.info" type="String" --]
[#-- @ftlvariable name="theme.success" type="String" --]
[#-- @ftlvariable name="theme.warning" type="String" --]
[#-- @ftlvariable name="nav" type="io.helidon.build.maven.sitegen.models.Nav" --]
[#-- @ftlvariable name="nav.glyph" type="io.helidon.build.maven.sitegen.models.Glyph" --]
[#-- @ftlvariable name="nav.glyph.value" type="String" --]
[#-- @ftlvariable name="nav.glyph.type" type="String" --]
[#-- @ftlvariable name="nav.title" type="String" --]
[#-- @ftlvariable name="nav.items" type="java.util.List<io.helidon.build.maven.sitegen.models.Nav>" --]
[#-- @ftlvariable name="navitem.pathprefix" type="String" --]
[#-- @ftlvariable name="navitem.glyph" type="io.helidon.build.maven.sitegen.models.Glyph" --]
[#-- @ftlvariable name="navitem.glyph.value" type="String" --]
[#-- @ftlvariable name="navitem.title" type="String" --]
[#-- @ftlvariable name="navitem.href" type="String" --]
[#-- @ftlvariable name="navitem.target" type="String" --]
[#-- @ftlvariable name="navitem.items" type="java.util.List<io.helidon.build.maven.sitegen.models.Nav>" --]
[#-- @ftlvariable name="allRoutes" type="java.util.List<String>" --]
[#-- @ftlvariable name="customLayoutEntries" type="java.util.Map<String,String>" --]
[#-- @ftlvariable name="bindings" type="java.util.Map<String,String>" --]
[#-- @ftlvariable name="navRoutes" type="java.util.Set<String>" --]
[#-- @ftlvariable name="pages" type="java.util.Map<String,io.helidon.build.maven.sitegen.models.Page>" --]
[#-- @ftlvariable name="page.target" type="String" --]
[#-- @ftlvariable name="page.metadata.h1" type="String" --]
[#-- @ftlvariable name="page.metadata.title" type="String" --]
[#-- @ftlvariable name="page.metadata.h1Prefix" type="String" --]
[#-- @ftlvariable name="page.metadata.keywords" type="String" --]
[#-- @ftlvariable name="page.metadata.description" type="String" --]
[#-- @ftlvariable name="type" type="String" --]
[#-- @ftlvariable name="entry.location" type="String" --]
[#-- @ftlvariable name="entry.text" type="String" --]
[#-- @ftlvariable name="entry.title" type="String" --]
[#-- @ftlvariable name="role" type="String" --]
[#-- @ftlvariable name="item.text" type="String" --]
[#-- @ftlvariable name="item.content" type="String" --]
[#-- @ftlvariable name="metadata" type="io.helidon.build.maven.sitegen.models.Page.Metadata" --]
[#-- @ftlvariable name="metadata.description" type="String" --]
[#-- @ftlvariable name="metadata.keywords" type="String" --]
[#-- @ftlvariable name="metadata.title" type="String" --]
[#-- @ftlvariable name="header.favicon" type="io.helidon.build.maven.sitegen.models.WebResource" file="templates/vuetify/index.ftl" --]
[#-- @ftlvariable name="header.favicon.type" type="String" file="templates/vuetify/index.ftl" --]
[#-- @ftlvariable name="header.favicon.location" type="String" file="templates/vuetify/index.ftl" --]
[#-- @ftlvariable name="header.stylesheets" type="java.util.List<io.helidon.build.maven.sitegen.models.WebResource>" file="templates/vuetify/index.ftl" --]
[#-- @ftlvariable name="stylesheet.location" type="String" --]
[#-- @ftlvariable name="searchEntries" type="java.util.List<io.helidon.build.maven.sitegen.models.SearchEntry>" --]
[#-- @ftlvariable name="helper" type="io.helidon.build.maven.sitegen.freemarker.HelperHashModel" --]
[#-- @ftlvariable name="id" type="String" --]
[#-- @ftlvariable name="document" type="org.asciidoctor.ast.Document" --]
[#-- @ftlvariable name="body" type="java.util.List<org.asciidoctor.ast.Row>" file="templates/vuetify/block_table.ftl" --]
[#-- @ftlvariable name="header" type="java.util.List<org.asciidoctor.ast.Row>" file="templates/vuetify/block_table.ftl" --]
[#-- @ftlvariable name="columns" type="java.util.List<org.asciidoctor.ast.Column>" file="templates/vuetify/block_table.ftl" --]
[#-- @ftlvariable name="level" type="Integer" --]
[#-- @ftlvariable name="source" type="String" --]
[#-- @ftlvariable name="content" type="String" --]
[#-- @ftlvariable name="title" type="String" --]
[#-- @ftlvariable name="text" type="String" --]
[#-- @ftlvariable name="this" type="org.asciidoctor.ast.StructuralNode" --]
[#-- @ftlvariable name="attributes" type="java.util.Map" --]
[#-- @ftlvariable name="items" type="java.util.List<org.asciidoctor.ast.DescriptionListEntry>" --]
[#function getString s][/#function]
[#macro searchIndex title][/#macro]
[#macro searchIndex][/#macro]
[#macro passthroughfix][/#macro]
[#function imageUri s][/#function]
[#macro customLayout][/#macro]
[#macro vueBindings][/#macro]