#!/bin/bash
#
# Copyright (c) 2023, 2025 Oracle and/or its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ -h "${0}" ] ; then
  SCRIPT_PATH="$(readlink "${BASH_SOURCE[0]}")"
else
  SCRIPT_PATH="${BASH_SOURCE[0]}"
fi
BASEDIR=$(cd "$(dirname -- "${SCRIPT_PATH}")/.." || true ; pwd -P)

if [ "$(uname)" == "CYGWIN" ]; then
    JAVA_HOME=$(cygpath --unix "${JAVA_HOME}")
    JAVA_HOME=$(cygpath --path --windows "${JAVA_HOME}")
    BASEDIR=$(cygpath --path --windows "${BASEDIR}")
elif [ -n "${JAVA_HOME}" ]; then
    JAVA_EXE="${JAVA_HOME}/bin/java"
else
    JAVA_EXE="java"
    echo "[WARNING] JAVA_HOME is not set"
fi

HELIDON_CLI_CMD="${JAVA_EXE}"
if [ -n "${HELIDON_CLI_JAVA_OPTS}" ]; then
  HELIDON_CLI_CMD="${HELIDON_CLI_CMD} ${HELIDON_CLI_JAVA_OPTS}"
fi
HELIDON_CLI_CMD="${HELIDON_CLI_CMD} -jar ${BASEDIR}/helidon-cli.jar ${*}"

if [ "${HELIDON_CLI_DEBUG}" = "true" ]; then
    echo ""
    echo "[DEBUG] Use HELIDON_CLI_JAVA_OPTS environment property to setup JVM arguments"
    echo "[DEBUG] Distribution located at : ${BASEDIR}"
    echo "[DEBUG] Using java command : ${JAVA_EXE}"
    echo "[DEBUG] Command executed : ${HELIDON_CLI_CMD}"
    echo ""
fi

${HELIDON_CLI_CMD}
